//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
namespace scaffolding.Models
{
    internal class idcheckAttribute : ValidationAttribute
    {
        public override bool IsValid(object value)
        {
            int id = (int)value;
            return (id <= 500);
        }
    }
}