//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scaffolding.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class person
    {
        public int id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        [Required(ErrorMessage ="Age is Required")]
        [Range(18,50,ErrorMessage ="Age must be between 18 and 50")]
        public int age { get; set; }
        [Required(ErrorMessage = "Email ID is Required")]
        [DataType(DataType.EmailAddress)]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage = "Incorrect Email Format")]

        public string Email { get; set; }
        [Required(ErrorMessage = "Mobile number is Required")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{2})[-. ]?([0-9]{4})?([0-9]{3})?([0-9]{3})$", ErrorMessage = "Not a valid Phone number")]

        public string Mobile { get; set; }
    }
}
